import Head from "next/head";
import Image from "next/image";
import vercel from "../public/vercel.svg";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome to Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
 
  <div id="hero" className="hero route bg-image" 
      style={{backgroundImage: "url(assets/img/hero-bg.jpg)"}}>
    <div className="overlay-itro"></div>
    <div className="hero-content display-table">
      <div className="table-cell">
        <div className="container">
         
          <h1 className="hero-title mb-4">I am Basit Baig</h1>
          <p className="hero-subtitle"><span className="typed" data-typed-items="Designer, Developer, Freelancer, Photographer"></span></p>
           {/* <p className="pt-3"><a className="btn btn-primary btn js-scroll px-4" href="#about" role="button">Learn More</a></p>  */}
        </div>
      </div>
    </div>
  </div> 

  <main id="main">

  </main> 

 



{/* <div id="preloader"></div>
<a href="#" className="back-to-top d-flex align-items-center justify-content-center"><i className="bi bi-arrow-up-short"></i></a>
 */}

      
 

      {/* <main classNameNameName={`${styles.main} ${inter.classNameNameName}`}>

            <h1>Home Page</h1>
      </main> */}



    </>
  );
}
